table 'Fact table'
	lineageTag: 25edc64d-78a1-4e91-90de-320eb9ee154c

	column 'Item Identifier'
		dataType: string
		lineageTag: 66126e1b-3a5f-494e-a287-e54ee68190a8
		summarizeBy: none
		sourceColumn: Item Identifier

		annotation SummarizationSetBy = Automatic

	column 'Outlet Establishment Year'
		dataType: int64
		formatString: 0
		lineageTag: 7e58006f-aa6f-4c9a-95d8-2596faf8a4cd
		summarizeBy: sum
		sourceColumn: Outlet Establishment Year

		annotation SummarizationSetBy = Automatic

	column 'Outlet Identifier'
		dataType: string
		lineageTag: 1a4ec2c6-af4a-446a-8b63-ffea53a46770
		summarizeBy: none
		sourceColumn: Outlet Identifier

		annotation SummarizationSetBy = Automatic

	column 'Item Visibility'
		dataType: double
		lineageTag: be97faea-0284-4634-8a9d-44cf7a6993d3
		summarizeBy: sum
		sourceColumn: Item Visibility

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Item Weight'
		dataType: double
		lineageTag: c4f3abee-bb16-4263-8b2c-0bac04fb355f
		summarizeBy: sum
		sourceColumn: Item Weight

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Sales
		dataType: double
		lineageTag: b4d92792-3936-446b-b972-8fc0b58a08d1
		summarizeBy: sum
		sourceColumn: Sales

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Rating
		dataType: int64
		formatString: 0
		lineageTag: 45dc8b6d-9b54-4908-aa99-22864474d85e
		summarizeBy: sum
		sourceColumn: Rating

		annotation SummarizationSetBy = Automatic

	column 'Fat content id'
		dataType: int64
		formatString: 0
		lineageTag: b33db05e-d0ce-413a-9e95-ba7edbfc4ae9
		summarizeBy: none
		sourceColumn: Fat content id

		annotation SummarizationSetBy = Automatic

	column 'Item type id'
		dataType: int64
		formatString: 0
		lineageTag: a618a06d-deb5-4df2-bb4d-cd3b6f2c2310
		summarizeBy: none
		sourceColumn: Item type id

		annotation SummarizationSetBy = Automatic

	column 'Location type id'
		dataType: int64
		formatString: 0
		lineageTag: 47b084f9-9345-4d85-8539-e97583806ae2
		summarizeBy: none
		sourceColumn: Location type id

		annotation SummarizationSetBy = Automatic

	column 'Outlet id'
		dataType: int64
		formatString: 0
		lineageTag: 2f00b34d-4816-4ce3-af23-43f8dd87f7da
		summarizeBy: none
		sourceColumn: Outlet id

		annotation SummarizationSetBy = Automatic

	column 'Outlet type id'
		dataType: int64
		formatString: 0
		lineageTag: d0d7e5e0-e518-4934-97ea-1fa8e3b286b1
		summarizeBy: none
		sourceColumn: Outlet type id

		annotation SummarizationSetBy = Automatic

	partition 'Fact table' = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\GarrajuNaralasetti(Q\Downloads\BlinkIT Grocery Data.xlsx"), null, true),
				    #"BlinkIT Grocery Data_Sheet" = Source{[Item="BlinkIT Grocery Data",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(#"BlinkIT Grocery Data_Sheet", [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Item Fat Content", type text}, {"Item Identifier", type text}, {"Item Type", type text}, {"Outlet Establishment Year", Int64.Type}, {"Outlet Identifier", type text}, {"Outlet Location Type", type text}, {"Outlet Size", type text}, {"Outlet Type", type text}, {"Item Visibility", type number}, {"Item Weight", type number}, {"Sales", type number}, {"Rating", Int64.Type}}),
				    #"Replaced Value" = Table.ReplaceValue(#"Changed Type","reg","Regular",Replacer.ReplaceText,{"Item Fat Content"}),
				    #"Replaced Value1" = Table.ReplaceValue(#"Replaced Value","LF","Low Fat",Replacer.ReplaceText,{"Item Fat Content"}),
				    #"Replaced Value2" = Table.ReplaceValue(#"Replaced Value1","low fat","Low Fat",Replacer.ReplaceText,{"Item Fat Content"}),
				    #"Filtered Rows" = Table.SelectRows(#"Replaced Value2", each true),
				    #"Merged Queries" = Table.NestedJoin(#"Filtered Rows", {"Item Fat Content"}, #"Fat content", {"Item Fat Content"}, "Fat content", JoinKind.LeftOuter),
				    #"Expanded Fat content" = Table.ExpandTableColumn(#"Merged Queries", "Fat content", {"Fat content id"}, {"Fat content id"}),
				    #"Removed Columns" = Table.RemoveColumns(#"Expanded Fat content",{"Item Fat Content"}),
				    #"Merged Queries1" = Table.NestedJoin(#"Removed Columns", {"Item Type"}, #"Item type", {"Item Type"}, "Item type.1", JoinKind.LeftOuter),
				    #"Expanded Item type.1" = Table.ExpandTableColumn(#"Merged Queries1", "Item type.1", {"Item type id"}, {"Item type id"}),
				    #"Merged Queries2" = Table.NestedJoin(#"Expanded Item type.1", {"Outlet Location Type"}, #"Location type", {"Outlet Location Type"}, "Location type", JoinKind.LeftOuter),
				    #"Expanded Location type" = Table.ExpandTableColumn(#"Merged Queries2", "Location type", {"Location type id"}, {"Location type id"}),
				    #"Removed Columns1" = Table.RemoveColumns(#"Expanded Location type",{"Item Type", "Outlet Location Type"}),
				    #"Merged Queries3" = Table.NestedJoin(#"Removed Columns1", {"Outlet Size"}, #"Outlet size", {"Outlet Size"}, "Outlet size.1", JoinKind.LeftOuter),
				    #"Expanded Outlet size.1" = Table.ExpandTableColumn(#"Merged Queries3", "Outlet size.1", {"Outlet id"}, {"Outlet id"}),
				    #"Removed Columns2" = Table.RemoveColumns(#"Expanded Outlet size.1",{"Outlet Size"}),
				    #"Merged Queries4" = Table.NestedJoin(#"Removed Columns2", {"Outlet Type"}, #"Outlet type", {"Outlet Type"}, "Outlet type.1", JoinKind.LeftOuter),
				    #"Expanded Outlet type.1" = Table.ExpandTableColumn(#"Merged Queries4", "Outlet type.1", {"Outlet type id"}, {"Outlet type id"}),
				    #"Removed Columns3" = Table.RemoveColumns(#"Expanded Outlet type.1",{"Outlet Type"})
				in
				    #"Removed Columns3"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

