table 'Location type'
	lineageTag: dd728610-dbbe-447e-91fb-d3917ed63524

	column 'Outlet Location Type'
		dataType: string
		lineageTag: 9c764ec0-579e-4b26-bf56-baf8f93d27e0
		summarizeBy: none
		sourceColumn: Outlet Location Type

		annotation SummarizationSetBy = Automatic

	column 'Location type id'
		dataType: int64
		isKey
		formatString: 0
		lineageTag: 227bedce-84c7-4256-81b8-4780a13b21fa
		summarizeBy: none
		sourceColumn: Location type id

		annotation SummarizationSetBy = Automatic

	partition 'Location type' = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\GarrajuNaralasetti(Q\Downloads\BlinkIT Grocery Data.xlsx"), null, true),
				    #"BlinkIT Grocery Data_Sheet" = Source{[Item="BlinkIT Grocery Data",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(#"BlinkIT Grocery Data_Sheet", [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Item Fat Content", type text}, {"Item Identifier", type text}, {"Item Type", type text}, {"Outlet Establishment Year", Int64.Type}, {"Outlet Identifier", type text}, {"Outlet Location Type", type text}, {"Outlet Size", type text}, {"Outlet Type", type text}, {"Item Visibility", type number}, {"Item Weight", type number}, {"Sales", type number}, {"Rating", Int64.Type}}),
				    #"Removed Other Columns" = Table.SelectColumns(#"Changed Type",{"Outlet Location Type"}),
				    #"Removed Duplicates" = Table.Distinct(#"Removed Other Columns"),
				    #"Added Index" = Table.AddIndexColumn(#"Removed Duplicates", "Index", 1, 1, Int64.Type),
				    #"Renamed Columns" = Table.RenameColumns(#"Added Index",{{"Index", "Location type id"}})
				in
				    #"Renamed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

