table 'Outlet type'
	lineageTag: 44ecd70c-89bb-4fca-bcc5-1f32d4a4afa0

	column 'Outlet type id'
		dataType: int64
		isKey
		formatString: 0
		lineageTag: 4d7e7ab6-5f90-4673-b4a6-57825caef2e4
		summarizeBy: none
		sourceColumn: Outlet type id

		annotation SummarizationSetBy = Automatic

	column 'Outlet Type'
		dataType: string
		lineageTag: c1a0bc10-00bb-4fc0-b6bc-d0b194d96f9f
		summarizeBy: none
		sourceColumn: Outlet Type

		annotation SummarizationSetBy = Automatic

	partition 'Outlet type' = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\GarrajuNaralasetti(Q\Downloads\BlinkIT Grocery Data.xlsx"), null, true),
				    #"BlinkIT Grocery Data_Sheet" = Source{[Item="BlinkIT Grocery Data",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(#"BlinkIT Grocery Data_Sheet", [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Item Fat Content", type text}, {"Item Identifier", type text}, {"Item Type", type text}, {"Outlet Establishment Year", Int64.Type}, {"Outlet Identifier", type text}, {"Outlet Location Type", type text}, {"Outlet Size", type text}, {"Outlet Type", type text}, {"Item Visibility", type number}, {"Item Weight", type number}, {"Sales", type number}, {"Rating", Int64.Type}}),
				    #"Removed Other Columns" = Table.SelectColumns(#"Changed Type",{"Outlet Type"}),
				    #"Removed Duplicates" = Table.Distinct(#"Removed Other Columns"),
				    #"Added Index" = Table.AddIndexColumn(#"Removed Duplicates", "Index", 1, 1, Int64.Type),
				    #"Renamed Columns" = Table.RenameColumns(#"Added Index",{{"Index", "Outlet type id"}}),
				    #"Reordered Columns" = Table.ReorderColumns(#"Renamed Columns",{"Outlet type id", "Outlet Type"})
				in
				    #"Reordered Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

